version: "3.2"
services:
  mongo:
    image: "mongo:3.6"
    ports:
      - "27018:27017"
  fluentd-forwarder:
    build: ./fluentd
    depends_on:
      - fluentd-aggregator-a
      - fluentd-aggregator-b
    links:
      - fluentd-aggregator-a:fluentd-aggregator-a
      - fluentd-aggregator-b:fluentd-aggregator-b
    volumes:
      - ./fluentd/fluentd-forwarder.conf:/fluentd/etc/fluentd.conf
      - ./logs/sample.log:/var/log/test/sample.log
      - ./logs/sample.log.pos:/var/log/test/sample.log.pos
    command: ["fluentd", "-c", "/fluentd/etc/fluentd.conf"]
  fluentd-aggregator-a:
    build: ./fluentd
    depends_on:
      - mongo
    links:
      - mongo:mongo
    volumes:
      - ./fluentd/fluentd-aggregator.conf:/fluentd/etc/fluentd.conf
    command: ["fluentd", "-c", "/fluentd/etc/fluentd.conf"]
  fluentd-aggregator-b:
    build: ./fluentd
    depends_on:
      - mongo
    links:
      - mongo:mongo
    volumes:
      - ./fluentd/fluentd-aggregator.conf:/fluentd/etc/fluentd.conf
    command: ["fluentd", "-c", "/fluentd/etc/fluentd.conf"]
  